// <auto-generated />
using System;
using GUMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GUMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260702114518_AddBudgetPlanningOptions")]
    partial class AddBudgetPlanningOptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("GUMS.Data.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("GUMS.Data.Entities.ActivityCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeetingActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MembershipNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeetingActivityId");

                    b.HasIndex("MembershipNumber");

                    b.HasIndex("MeetingActivityId", "MembershipNumber")
                        .IsUnique();

                    b.ToTable("ActivityCompletions");
                });

            modelBuilder.Entity("GUMS.Data.Entities.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attended")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConsentDeclined")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConsentDeclinedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsentEmailDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConsentEmailReceived")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConsentFormDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConsentFormReceived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeetingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MembershipNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NightsAway")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PlanningToAttend")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SignedUp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("MembershipNumber");

                    b.HasIndex("MeetingId", "MembershipNumber")
                        .IsUnique();

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("GUMS.Data.Entities.AwardTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BronzeAwardedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GoldAwardedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("GoldChallengeComplete")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GoldChallengeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MembershipNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SilverAwardedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MembershipNumber")
                        .IsUnique();

                    b.ToTable("AwardTrackings");
                });

            modelBuilder.Entity("GUMS.Data.Entities.AwardedBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BadgeDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAwarded")
                        .HasColumnType("TEXT");

                    b.Property<string>("MembershipNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BadgeDefinitionId");

                    b.HasIndex("MembershipNumber", "BadgeDefinitionId")
                        .IsUnique();

                    b.ToTable("AwardedBadges");
                });

            modelBuilder.Entity("GUMS.Data.Entities.AwardedThemeAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAwarded")
                        .HasColumnType("TEXT");

                    b.Property<string>("MembershipNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Theme")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MembershipNumber", "Theme")
                        .IsUnique();

                    b.ToTable("AwardedThemeAwards");
                });

            modelBuilder.Entity("GUMS.Data.Entities.BadgeClause", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BadgeDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BadgeDefinitionId");

                    b.ToTable("BadgeClauses");
                });

            modelBuilder.Entity("GUMS.Data.Entities.BadgeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BadgeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredCompletions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Section")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillsBuilderName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Theme")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BadgeType");

                    b.HasIndex("Section");

                    b.HasIndex("Theme");

                    b.ToTable("BadgeDefinitions");
                });

            modelBuilder.Entity("GUMS.Data.Entities.BadgeStockItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwardTheme")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BadgeDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NightsAwayTier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReorderThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ThemeAwardLevel")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BadgeDefinitionId");

                    b.HasIndex("IsActive");

                    b.HasIndex("StockType");

                    b.ToTable("BadgeStockItems");
                });

            modelBuilder.Entity("GUMS.Data.Entities.BadgeStockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwardedBadgeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwardedThemeAwardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BadgeStockItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExpenseClaimId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BadgeStockItemId");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("TransactionType");

                    b.ToTable("BadgeStockTransactions");
                });

            modelBuilder.Entity("GUMS.Data.Entities.BankReconciliation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ReconciledBookBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StatementBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StatementDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StatementDate");

                    b.HasIndex("Status");

                    b.ToTable("BankReconciliations");
                });

            modelBuilder.Entity("GUMS.Data.Entities.CostCentre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CostCentres");
                });

            modelBuilder.Entity("GUMS.Data.Entities.CreditTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("MembershipNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourcePaymentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetPaymentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("MembershipNumber");

                    b.HasIndex("SourcePaymentId");

                    b.HasIndex("TargetPaymentId");

                    b.HasIndex("TransactionId");

                    b.ToTable("CreditTransactions");
                });

            modelBuilder.Entity("GUMS.Data.Entities.DataRemovalLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DataExported")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MembershipNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RemovalDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("RemovedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MembershipNumber");

                    b.HasIndex("RemovalDate");

                    b.ToTable("DataRemovalLogs");
                });

            modelBuilder.Entity("GUMS.Data.Entities.EmergencyContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryPhone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("EmergencyContacts");
                });

            modelBuilder.Entity("GUMS.Data.Entities.EventAdditionalPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactRelationship")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("MeetingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.ToTable("EventAdditionalPeople");
                });

            modelBuilder.Entity("GUMS.Data.Entities.EventBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LeadersPay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeetingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlannedAdultCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId")
                        .IsUnique();

                    b.ToTable("EventBudgets");
                });

            modelBuilder.Entity("GUMS.Data.Entities.EventBudgetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("CostStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventBudgetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExpenseAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventBudgetId");

                    b.HasIndex("ExpenseAccountId");

                    b.ToTable("EventBudgetItems");
                });

            modelBuilder.Entity("GUMS.Data.Entities.EventContactOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MeetingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MembershipNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryPhone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("MeetingId", "MembershipNumber");

                    b.ToTable("EventContactOverrides");
                });

            modelBuilder.Entity("GUMS.Data.Entities.EventHomeContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeetingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.ToTable("EventHomeContacts");
                });

            modelBuilder.Entity("GUMS.Data.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CostCentreId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpenseAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExpenseClaimId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaidFromAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CostCentreId");

                    b.HasIndex("Date");

                    b.HasIndex("ExpenseAccountId");

                    b.HasIndex("ExpenseClaimId");

                    b.HasIndex("MeetingId");

                    b.HasIndex("PaidFromAccountId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("GUMS.Data.Entities.ExpenseClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaidFromAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaymentMethod")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SettledDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PaidFromAccountId");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionId");

                    b.ToTable("ExpenseClaims");
                });

            modelBuilder.Entity("GUMS.Data.Entities.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CostCentreId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CostPerAttendee")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CostPerLeader")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IncomeAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaderNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MeetingType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaymentDeadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgrammeNotes")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CostCentreId");

                    b.HasIndex("Date");

                    b.HasIndex("IncomeAccountId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("GUMS.Data.Entities.MeetingActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BadgeClauseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BadgeDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresConsent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UmaDefinitionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BadgeClauseId");

                    b.HasIndex("BadgeDefinitionId");

                    b.HasIndex("MeetingId");

                    b.HasIndex("UmaDefinitionId");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("GUMS.Data.Entities.MemberCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("MembershipNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MembershipNumber")
                        .IsUnique();

                    b.ToTable("MemberCredits");
                });

            modelBuilder.Entity("GUMS.Data.Entities.NightsAwayBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAwarded")
                        .HasColumnType("TEXT");

                    b.Property<string>("MembershipNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Milestone")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MembershipNumber", "Milestone")
                        .IsUnique();

                    b.ToTable("NightsAwayBadges");
                });

            modelBuilder.Entity("GUMS.Data.Entities.Patrol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmblemBadgeDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Section")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmblemBadgeDefinitionId");

                    b.HasIndex("Section", "Name")
                        .IsUnique();

                    b.ToTable("Patrols");
                });

            modelBuilder.Entity("GUMS.Data.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CreditApplied")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IncomeAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MembershipNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaymentMethod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RefundAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefundDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RefundTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TermId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("IncomeAccountId");

                    b.HasIndex("MeetingId");

                    b.HasIndex("MembershipNumber");

                    b.HasIndex("RefundTransactionId");

                    b.HasIndex("Status");

                    b.HasIndex("TermId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("GUMS.Data.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Allergies")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateJoined")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime?>("DateLeft")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Disabilities")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExtraNightsAway")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDataRemoved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MembershipNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PatrolId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatrolRole")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoPermission")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Section")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDataRemoved");

                    b.HasIndex("MembershipNumber")
                        .IsUnique();

                    b.HasIndex("PatrolId");

                    b.HasIndex("PatrolId", "PatrolRole")
                        .IsUnique()
                        .HasFilter("\"PatrolRole\" <> 0");

                    b.ToTable("Persons", t =>
                        {
                            t.HasCheckConstraint("CK_Person_PatrolRole_Requires_Patrol", "\"PatrolRole\" = 0 OR \"PatrolId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("GUMS.Data.Entities.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SubsAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartDate", "EndDate");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("GUMS.Data.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVoided")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("VoidedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("PaymentId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("GUMS.Data.Entities.TransactionLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BankReconciliationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CostCentreId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Credit")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Debit")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BankReconciliationId");

                    b.HasIndex("CostCentreId");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionLines");
                });

            modelBuilder.Entity("GUMS.Data.Entities.UmaDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Minutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Theme")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Theme");

                    b.ToTable("UmaDefinitions");
                });

            modelBuilder.Entity("GUMS.Data.Entities.UnitBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FinancialYearEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FinancialYearEnd")
                        .IsUnique();

                    b.ToTable("UnitBudgets");
                });

            modelBuilder.Entity("GUMS.Data.Entities.UnitBudgetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Allocation")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExpenseAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitBudgetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseAccountId");

                    b.HasIndex("UnitBudgetId");

                    b.ToTable("UnitBudgetItems");
                });

            modelBuilder.Entity("GUMS.Data.Entities.UnitConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AccountsLockedUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultLocationAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultLocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("DefaultMeetingEndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("DefaultMeetingStartTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultSubsAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("DistrictCommissionerName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DistrictCommissionerPhone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DivisionCommissionerName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DivisionCommissionerPhone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("FinancialYearEndDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FinancialYearEndMonth")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("JoiningFeeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("MeetingDayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentTermDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UnitConfigurations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GUMS.Data.Entities.ActivityCompletion", b =>
                {
                    b.HasOne("GUMS.Data.Entities.MeetingActivity", "MeetingActivity")
                        .WithMany("Completions")
                        .HasForeignKey("MeetingActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetingActivity");
                });

            modelBuilder.Entity("GUMS.Data.Entities.Attendance", b =>
                {
                    b.HasOne("GUMS.Data.Entities.Meeting", "Meeting")
                        .WithMany("Attendances")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("GUMS.Data.Entities.AwardedBadge", b =>
                {
                    b.HasOne("GUMS.Data.Entities.BadgeDefinition", "BadgeDefinition")
                        .WithMany()
                        .HasForeignKey("BadgeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BadgeDefinition");
                });

            modelBuilder.Entity("GUMS.Data.Entities.BadgeClause", b =>
                {
                    b.HasOne("GUMS.Data.Entities.BadgeDefinition", "BadgeDefinition")
                        .WithMany("Clauses")
                        .HasForeignKey("BadgeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BadgeDefinition");
                });

            modelBuilder.Entity("GUMS.Data.Entities.BadgeStockItem", b =>
                {
                    b.HasOne("GUMS.Data.Entities.BadgeDefinition", "BadgeDefinition")
                        .WithMany()
                        .HasForeignKey("BadgeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BadgeDefinition");
                });

            modelBuilder.Entity("GUMS.Data.Entities.BadgeStockTransaction", b =>
                {
                    b.HasOne("GUMS.Data.Entities.BadgeStockItem", "BadgeStockItem")
                        .WithMany("Transactions")
                        .HasForeignKey("BadgeStockItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BadgeStockItem");
                });

            modelBuilder.Entity("GUMS.Data.Entities.CreditTransaction", b =>
                {
                    b.HasOne("GUMS.Data.Entities.Payment", "SourcePayment")
                        .WithMany()
                        .HasForeignKey("SourcePaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GUMS.Data.Entities.Payment", "TargetPayment")
                        .WithMany()
                        .HasForeignKey("TargetPaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GUMS.Data.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourcePayment");

                    b.Navigation("TargetPayment");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("GUMS.Data.Entities.EmergencyContact", b =>
                {
                    b.HasOne("GUMS.Data.Entities.Person", "Person")
                        .WithMany("EmergencyContacts")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("GUMS.Data.Entities.EventAdditionalPerson", b =>
                {
                    b.HasOne("GUMS.Data.Entities.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("GUMS.Data.Entities.EventBudget", b =>
                {
                    b.HasOne("GUMS.Data.Entities.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("GUMS.Data.Entities.EventBudgetItem", b =>
                {
                    b.HasOne("GUMS.Data.Entities.EventBudget", "EventBudget")
                        .WithMany("Items")
                        .HasForeignKey("EventBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GUMS.Data.Entities.Account", "ExpenseAccount")
                        .WithMany()
                        .HasForeignKey("ExpenseAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EventBudget");

                    b.Navigation("ExpenseAccount");
                });

            modelBuilder.Entity("GUMS.Data.Entities.EventContactOverride", b =>
                {
                    b.HasOne("GUMS.Data.Entities.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("GUMS.Data.Entities.EventHomeContact", b =>
                {
                    b.HasOne("GUMS.Data.Entities.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("GUMS.Data.Entities.Expense", b =>
                {
                    b.HasOne("GUMS.Data.Entities.CostCentre", "CostCentre")
                        .WithMany()
                        .HasForeignKey("CostCentreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GUMS.Data.Entities.Account", "ExpenseAccount")
                        .WithMany()
                        .HasForeignKey("ExpenseAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GUMS.Data.Entities.ExpenseClaim", "ExpenseClaim")
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseClaimId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GUMS.Data.Entities.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GUMS.Data.Entities.Account", "PaidFromAccount")
                        .WithMany()
                        .HasForeignKey("PaidFromAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GUMS.Data.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CostCentre");

                    b.Navigation("ExpenseAccount");

                    b.Navigation("ExpenseClaim");

                    b.Navigation("Meeting");

                    b.Navigation("PaidFromAccount");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("GUMS.Data.Entities.ExpenseClaim", b =>
                {
                    b.HasOne("GUMS.Data.Entities.Account", "PaidFromAccount")
                        .WithMany()
                        .HasForeignKey("PaidFromAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GUMS.Data.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PaidFromAccount");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("GUMS.Data.Entities.Meeting", b =>
                {
                    b.HasOne("GUMS.Data.Entities.CostCentre", "CostCentre")
                        .WithMany()
                        .HasForeignKey("CostCentreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GUMS.Data.Entities.Account", "IncomeAccount")
                        .WithMany()
                        .HasForeignKey("IncomeAccountId");

                    b.Navigation("CostCentre");

                    b.Navigation("IncomeAccount");
                });

            modelBuilder.Entity("GUMS.Data.Entities.MeetingActivity", b =>
                {
                    b.HasOne("GUMS.Data.Entities.BadgeClause", "BadgeClause")
                        .WithMany()
                        .HasForeignKey("BadgeClauseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GUMS.Data.Entities.BadgeDefinition", "BadgeDefinition")
                        .WithMany()
                        .HasForeignKey("BadgeDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GUMS.Data.Entities.Meeting", "Meeting")
                        .WithMany("MeetingActivities")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GUMS.Data.Entities.UmaDefinition", "UmaDefinition")
                        .WithMany()
                        .HasForeignKey("UmaDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BadgeClause");

                    b.Navigation("BadgeDefinition");

                    b.Navigation("Meeting");

                    b.Navigation("UmaDefinition");
                });

            modelBuilder.Entity("GUMS.Data.Entities.Patrol", b =>
                {
                    b.HasOne("GUMS.Data.Entities.BadgeDefinition", "EmblemBadge")
                        .WithMany()
                        .HasForeignKey("EmblemBadgeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmblemBadge");
                });

            modelBuilder.Entity("GUMS.Data.Entities.Payment", b =>
                {
                    b.HasOne("GUMS.Data.Entities.Account", "IncomeAccount")
                        .WithMany()
                        .HasForeignKey("IncomeAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GUMS.Data.Entities.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GUMS.Data.Entities.Transaction", "RefundTransaction")
                        .WithMany()
                        .HasForeignKey("RefundTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GUMS.Data.Entities.Term", "Term")
                        .WithMany("Payments")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("IncomeAccount");

                    b.Navigation("Meeting");

                    b.Navigation("RefundTransaction");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("GUMS.Data.Entities.Person", b =>
                {
                    b.HasOne("GUMS.Data.Entities.Patrol", "Patrol")
                        .WithMany("Members")
                        .HasForeignKey("PatrolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Patrol");
                });

            modelBuilder.Entity("GUMS.Data.Entities.Transaction", b =>
                {
                    b.HasOne("GUMS.Data.Entities.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("GUMS.Data.Entities.TransactionLine", b =>
                {
                    b.HasOne("GUMS.Data.Entities.Account", "Account")
                        .WithMany("TransactionLines")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GUMS.Data.Entities.BankReconciliation", "BankReconciliation")
                        .WithMany("ReconciledLines")
                        .HasForeignKey("BankReconciliationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GUMS.Data.Entities.CostCentre", "CostCentre")
                        .WithMany("TransactionLines")
                        .HasForeignKey("CostCentreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GUMS.Data.Entities.Transaction", "Transaction")
                        .WithMany("Lines")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("BankReconciliation");

                    b.Navigation("CostCentre");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("GUMS.Data.Entities.UnitBudgetItem", b =>
                {
                    b.HasOne("GUMS.Data.Entities.Account", "ExpenseAccount")
                        .WithMany()
                        .HasForeignKey("ExpenseAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GUMS.Data.Entities.UnitBudget", "UnitBudget")
                        .WithMany("Items")
                        .HasForeignKey("UnitBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseAccount");

                    b.Navigation("UnitBudget");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GUMS.Data.Entities.Account", b =>
                {
                    b.Navigation("TransactionLines");
                });

            modelBuilder.Entity("GUMS.Data.Entities.BadgeDefinition", b =>
                {
                    b.Navigation("Clauses");
                });

            modelBuilder.Entity("GUMS.Data.Entities.BadgeStockItem", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("GUMS.Data.Entities.BankReconciliation", b =>
                {
                    b.Navigation("ReconciledLines");
                });

            modelBuilder.Entity("GUMS.Data.Entities.CostCentre", b =>
                {
                    b.Navigation("TransactionLines");
                });

            modelBuilder.Entity("GUMS.Data.Entities.EventBudget", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GUMS.Data.Entities.ExpenseClaim", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("GUMS.Data.Entities.Meeting", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("MeetingActivities");
                });

            modelBuilder.Entity("GUMS.Data.Entities.MeetingActivity", b =>
                {
                    b.Navigation("Completions");
                });

            modelBuilder.Entity("GUMS.Data.Entities.Patrol", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("GUMS.Data.Entities.Person", b =>
                {
                    b.Navigation("EmergencyContacts");
                });

            modelBuilder.Entity("GUMS.Data.Entities.Term", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("GUMS.Data.Entities.Transaction", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("GUMS.Data.Entities.UnitBudget", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
